### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by oczki** [rr-/malgraph4#93]
- [x] admin password (see `local.php`)
- [x] ~~htaccess~~ config to fix drl.pl url (rr-)
- [x] change domain to point to drl.pl
- [x] when maintenance shows up ~~swap htaccess~~ change config
- [x] send changelog to rr- to post it on ~~club forums~~ github releases page
- [x] club description (update changelog url) and title
- [x] generate wiki page for achievements (rr-)
- [x] block users that requested it on mg3
- [x] make sure cron works and dequeues users
